name: Update Projects Page

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-projects-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ✅ Ensures we have full history to rebase

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch projects from GitHub API
        id: fetch_repos
        run: |
          REPOS_JSON=$(curl -s "https://api.github.com/users/pawanxcaliber/repos?per_page=100&sort=updated")

          if [ "$(echo "$REPOS_JSON" | grep -c "name")" -eq "0" ]; then
            echo "::error::Failed to fetch repositories from GitHub API."
            exit 1
          fi

          PROJECTS_HTML=""
          for row in $(echo "${REPOS_JSON}" | jq -r '.[] | @base64'); do
              _jq() {
                  echo ${row} | base64 --decode | jq -r ${1}
              }
              NAME=$(_jq '.name')
              DESCRIPTION=$(_jq '.description')
              HTML_URL=$(_jq '.html_url')

              PROJECTS_HTML+="
              <div class='project-item'>
                  <h3>$NAME</h3>
                  <p>${DESCRIPTION:-No description provided}</p>
                  <a href='$HTML_URL' class='project-link' target='_blank' rel='noopener noreferrer'>View on GitHub</a>
              </div>
              "
          done

          echo "PROJECTS_HTML<<EOF" >> $GITHUB_ENV
          echo "$PROJECTS_HTML" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update projects.html file
        run: |
          sed '/<!-- PROJECTS_PLACEHOLDER -->/{
            r /dev/stdin
            d
          }' projects-template.html > projects.html <<< "${{ env.PROJECTS_HTML }}"

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # ✅ Ensure we have the latest changes before committing
          git pull --rebase origin main

          git add projects.html
          git commit -m "Auto-update projects page via GitHub Actions" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
